### ISSUE TITLE
Hex string is too short

### ISSUE THREAD

**Issue by MichaelTheriot** [zenozeng/color-hash#19]
When I use high saturation values the hex string becomes too short.

``` javascript
var colorHash = new ColorHash({saturation: 0.9});
colorHash.hex('test'); // #f252d
```

**Comment by zenozeng** [comment]
Seems due to https://github.com/zenozeng/color-hash/blob/master/lib/color-hash.js#L97.
I will fix it and add unit tests tomorrow, I have too much things to do today.

**Comment by zenozeng** [comment]
Or, you can pull a request if you are interested in fixing this.

**Comment by zenozeng** [comment]
Sorry for being late. It should work in color-hash@1.0.3.
