### ISSUE TITLE
Generates the same color for long strings of equal length

### ISSUE THREAD

**Issue by adius** [zenozeng/color-hash#21]
It seems like it generates the same color for long strings if they have the same number of characters.

E.g.

```
long sentence abc
long sentence def
long sentence xyz
```

all generate the same color.

Any thoughts on this?

**Comment by zenozeng** [comment]
Sorry for my late response. I think this is because these string has same hash result when using current default hash function.

![image](https://cloud.githubusercontent.com/assets/2544489/13722691/f4ff8348-e888-11e5-831c-4fa64e6c20dc.png)

**Comment by zenozeng** [comment]
Current default hash function: https://github.com/zenozeng/color-hash/blob/34f5e0ef412cbb2b33561f6bc4f318e5bee78022/lib/bkdr-hash.js

**Comment by zenozeng** [comment]
@adius May be you can use a custom hash function, for example:

``` javascript
var customHash = function(str) {
    var hash = 0;
    for(var i = 0; i < str.length; i++) {
        hash += str.charCodeAt(i);
    }
    return hash;
};
var colorHash = new ColorHash({hash: customHash});
```

**Comment by adius** [comment]
Yeah I know that it's because of the hash function =D
What I was implying is "shouldn't the default hash function be better than this!?"

**Comment by shahinism** [comment]
Maybe using [lose lose](http://www.cse.yorku.ca/~oz/hash.html) algorithm be a more reliable approach as default hash function.

**Comment by emilbayes** [comment]
@shahinism lose lose is what @zenozeng suggested above

**Comment by vaibhavpatil123** [comment]
IF STRING IS OF BELOW TYPE THEN GIVING WRONG HEX CODE
192.168.1.2
overall this plugin is good ! +1
