### ISSUE TITLE
Can I always use white text with these colors?

### ISSUE THREAD

**Issue by jenstornell** [zenozeng/color-hash#23]
The colors I've tested are safe to use with white text on. I guess these colors always have some grade of darkness/colors in them to make white text work on them. For example bright yellow and white will never be generated as colors?

Can you confirm that white text will always work with these colors?

**Comment by lmj0011** [comment]
project seems dead bro

**Comment by toobulkeh** [comment]
You can set a custom lightness variable which would guarantee darker colors:
```js
var colorHash = new ColorHash({lightness: [0.35, 0.5, 0.65]});
```

https://github.com/zenozeng/color-hash#custom-lightness
