### ISSUE TITLE
color-hash.d.ts

### ISSUE THREAD

**Issue by JohannesHoppe** [zenozeng/color-hash#24]
I came across this library and wanted to add this to my TypeScript-project (TypeScript 2.3).
I have no time to upload this to DefinitelyTyped or send a PR. So I will just leave it here!

Have fun!

```
// Type definitions for color-hash 1.0.3
// Project: https://github.com/zenozeng/color-hash

declare module "color-hash" {

    /**
     * Color Hash Class
     *
     * @class
     */
    class ColorHash {

        /**
         * Returns the hash in [h, s, l].
         * Note that H ∈ [0, 360); S ∈ [0, 1]; L ∈ [0, 1];
         *
         * @param {String} str string to hash
         * @returns {Array} [h, s, l]
         */
        hsl(str: string): [number, number, number];

        /**
         * Returns the hash in [r, g, b].
         * Note that R, G, B ∈ [0, 255]
         *
         * @param {String} str string to hash
         * @returns {Array} [r, g, b]
         */
        rgb(str: string): [number, number, number];

        /**
         * Returns the hash in hex
         *
         * @param {String} str string to hash
         * @returns {String} hex with #
         */
        hex(str: string): string;
    }

    namespace ColorHash {}
    export = ColorHash;
}
```

**Comment by JohannesHoppe** [comment]
Just for the records, `namespace ColorHash {}` is required because of this: 
https://github.com/Microsoft/TypeScript/issues/5073

**Comment by Fredz66** [comment]
You can add :
`constructor(options?: any);`
after :
`class ColorHash {`
to be able to use options, like :
`let colorHash = new ColorHash({ hash: customHash });`

I don't know if this technique is clean but at least it does work.

**Comment by ksocha** [comment]
@JohannesHoppe I've created a PR in DT and listed you as a co-author.

**Comment by JohannesHoppe** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41524
