### ISSUE TITLE
Generates same colors for even small strings ending with number

### ISSUE THREAD

**Issue by kheealam** [zenozeng/color-hash#27]
Looks like it is generating the same color for the strings just different by end number.

Example:
`myView1`
`myView2`

Same color. Any Idea?

**Comment by zenozeng** [comment]
See #21

**Comment by lucas-bremond** [comment]
The default hash function is unusable, as using numbers to differentiate names is ultra common.
What is the rationale for not updating it?

**Comment by zenozeng** [comment]
@lucas-bremond I am considering changing default hash function to sha256 in v2, but i am a little bit worrying about the size issue.

**Comment by larrifax** [comment]
@zenozeng What about using the (soon to be) standardized Web Cryptography API's digest method? https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest

It shouldn't add any size to the library, and the browser support seems to be good amongs recent browser versions (even IE 11 has it).
