### ISSUE TITLE
Warning during compilation: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by valentinstn** [zenozeng/color-hash#36]
Hi all,

first of all, thanks for this neat library! We started to use it as part of our Angular project. 

We have just a minor problem: During compilation, the lib throws this warning, probably because the lib was packaged as `umd` module, which webpack doesn't like. 

Is there any plan to build this module differently?

**Comment by zenozeng** [comment]
@valentinstn Hi, color-hash@2.0.1 now ships with CommonJS module.

**Comment by valentinstn** [comment]
Thank you @zenozeng . Works like charm!
