### ISSUE TITLE
Default saturation changed in v2

### ISSUE THREAD

**Issue by artu-ole** [zenozeng/color-hash#37]
Here's a simple demo that demonstrates this unexpected change https://jsfiddle.net/artuole/6d4m0pj7/

version 1.1.1 on the left vs 2.0.0 on the right
![image](https://user-images.githubusercontent.com/15938416/121188504-d9733d80-c871-11eb-8fb5-2e067133d607.png)

**Comment by artu-ole** [comment]
Behavior difference must've been due to change in order of default saturation and lightness arrays.
Issue can be worked around by overriding saturation and lightness to match old colors, https://jsfiddle.net/artuole/1g7jqerm/

**Comment by zenozeng** [comment]
Thanks @artu-ole , I added a note for this.
